name: CI - NetSentry Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run FastAPI sanity test
      run: |
        python - <<'PYCODE'
        from fastapi.testclient import TestClient
        from app.main import app
        client = TestClient(app)
        r = client.get("/")
        assert r.status_code == 200
        print("✅ API OK:", r.json())
        PYCODE

    - name: Run CLI sanity test
      run: |
        python src/netsentry/cli.py check --url https://example.com || true

    - name: Build Docker image
      run: |
        docker build -t netsentry-ci:latest .
