name: CI - NetSentry Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: List repository files
      run: |
        echo "Current working directory: $(pwd)"
        echo "Listing contents of repository:"
        tree -L 2 || ls -R .

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run FastAPI sanity test
      run: |
        source .venv/bin/activate
        python - <<'PYCODE'
        from fastapi.testclient import TestClient
        from app.main import app
        client = TestClient(app)
        r = client.get("/")
        assert r.status_code == 200
        print("✅ API OK:", r.json())
        PYCODE

    - name: Run CLI sanity test
      run: |
        source .venv/bin/activate
        python src/netsentry/cli.py check --url https://example.com || true

    - name: Build Docker image
      run: |
        docker build -t netsentry-ci:latest .

    - name: Upload build logs and config snapshot
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: |
          requirements.txt
          Dockerfile
          .github/workflows/ci.yml